id: 1c0c306594fe4a9f89ec376aeed1e429
title: Toh_731-Tara_Who_Protects_from_Eight_Dangers-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-094-008
  eft-text-version: 1.1.3 2020
